apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vibe-kanban-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibe-kanban
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vibe-kanban
  template:
    metadata:
      labels:
        app: vibe-kanban
    spec:
      containers:
        - name: vibe-kanban
          image: ghcr.io/chalharu/vibe-stack-docker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8080"
            - name: HOST
              value: "0.0.0.0"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: vibe-data
              mountPath: /home/runner/.local/share/vibe-kanban
      volumes:
        - name: vibe-data
          persistentVolumeClaim:
            claimName: vibe-kanban-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vibe-kanban
spec:
  type: ClusterIP
  selector:
    app: vibe-kanban
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
