name: Automerge renovate PRs

on:
  pull_request_target:
    types: [labeled, unlabeled, opened, synchronize]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auto-merge when checks pass
        uses: actions-ecosystem/action-auto-merge@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
          required_contexts: build
