name: Automerge renovate PRs

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize]
  # For pull_request_target only handle label events and verify sender
  pull_request_target:
    types: [labeled]

permissions:
  pull-requests: write
  checks: read
  contents: read

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auto-merge when checks pass
        if: >
          contains(github.event.pull_request.labels.*.name, 'automerge') &&
          !contains(github.event.pull_request.labels.*.name, 'major') &&
          (
            github.event.pull_request.head.repo.full_name == github.repository ||
            (
              github.event_name == 'pull_request_target' &&
              github.event.action == 'labeled' &&
              github.event.label.name == 'automerge' &&
              (
                github.event.sender.login == 'renovate[bot]' ||
                github.event.sender.login == 'dependabot[bot]'
              )
            )
          )
        uses: actions-ecosystem/action-auto-merge@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
          required_contexts: build
