name: Build and Publish

permissions:
  contents: read
  packages: write

on:
  push:
    branches: ["001-vibe-kanban-kubernetes", "main"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and load image for smoke test (runner-arch)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          # omit platforms to build for the runner's architecture and load it locally
          tags: ghcr.io/${{ github.repository }}:test-${{ github.sha }}
          load: true
          push: false

      - name: Run smoke test (against loaded image)
        run: ./ci/smoke_test.sh ghcr.io/${{ github.repository }}:test-${{ github.sha }}

      - name: Build and push image (multi-arch)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
          push: true
